---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  collections:
    - community.kubernetes

  tasks:
    - name: Delete namespace
      community.kubernetes.k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'
        state: absent
        wait: true

    - name: Delete RBAC resources
      community.kubernetes.k8s:
        definition: "{{ lookup('template', '/'.join([deploy_dir, item])) }}"
        namespace: '{{ namespace }}'
        state: absent
        wait: true
      with_items:
        - role.yaml
        - role_binding.yaml
        - service_account.yaml

    - name: Delete Custom Resource Definition
      community.kubernetes.k8s:
        definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/pacifica.github.io_pacificas_crd.yaml'])) }}"
        state: absent
        wait: true
